### ISSUE TITLE
can we access block value like hash?

### ISSUE THREAD

**Issue by hcyildirim** [heartcombo/has_scope#100]
Hi,

I have scope like below:

```
has_scope :by_distance, using: %i[lat lon], type: :hash do |controller, scope, value|
    scope.by_distance(value[0], value[1], controller.current_user)
end
```

And i want to access value like `lat` or `lon`, how can i do that?

**Comment by TylerRick** [comment]
Are you proposing accessing those values as `value[:lat], value[:lon]` rather than `value[0], value[1]`?That does read more nicely.

I was just looking (with a debugger) at the part of code that passes values to the block and it looks like it's an array because it's using `values_at`:
```
   161:     if type == :boolean && !options[:allow_blank]
   162:       block ? block.call(self, target) : target.send(scope)
   163:     elsif value && options.key?(:using)
=> 164:       value = value.values_at(*options[:using])
   165:       block ? block.call(self, target, value) : target.send(scope, *value)
```

I think if we just changed that to `value.slice(*options[:using])` instead, it would work as you're describing.

But would you only want it to do that for the value that is passed to the block, and *not* for the values that get passed to the scope (` target.send(scope, *value)`) when not using a block? I think we'd have to keep passing the values to the scope as position arguments since most model scope blocks expect them in that way.

That could work, but would be inconsistent.

The other concern, of course, is that it would break `has_scope` blocks that expect the values as positional arguments (not backwards compatible)...

**Comment by carlosantoniodasilva** [comment]
We could possibly make it work in a backwards-compatible way by using some structure that accepted indexes and hash-like access, for example a Struct:

```ruby
>> st = Struct.new(:lat, :lon).new('the lat 123', 'the long 456')
=> #<struct lat="the lat 123", lon="the long 456">
>> st.lat
=> "the lat 123"
>> st[0]
=> "the lat 123"
>> st.lon
=> "the long 456"
>> st[1]
=> "the long 456"
```

That said, you can use Array destructuring in Ruby in order to receive named arguments directly into the block, something like this should work I think:

```ruby
has_scope :by_distance, using: %i[lat lon], type: :hash do |controller, scope, (lat, lon)|
  scope.by_distance(lat, lon, controller.current_user)
end
```

This way you don't need to deal with indexes or hash keys, just variables. Because that's already possible today, I think there's no need to extend has scope's functionality to support hash key like access, but I'm happy to discuss it further if you think otherwise. Thanks!
