### ISSUE TITLE
Default values not updating

### ISSUE THREAD

**Issue by maxrosecollins** [heartcombo/has_scope#114]
I have the following in my controller
`has_scope :by_date,
                  default:     {
                    from: (Date.current - 1.week).strftime('%Y-%m-%d'),
                    to:   Date.current.strftime('%Y-%m-%d')
                  },
                  using:       %i[from to]`

The date doesn't update each day unless I redeploy my application.

I have also tried this 

```
previous_date = ->() { (Date.current - 1.day).strftime('%Y-%m-%d') }
current_date = ->() { Date.current.strftime('%Y-%m-%d') }

has_scope :by_date, default: { from: previous_date.call, to: current_date.call }, using: %i[from to]
```
Any ideas?

**Comment by maxrosecollins** [comment]
This fixed it.

`default: lambda {
    {
      from: (Time.current - 1.day).strftime('%Y-%m-%d'),
      to:   Time.current.strftime('%Y-%m-%d')
    }
}`

**Comment by carlosantoniodasilva** [comment]
@maxrosecollins thanks for reporting back.

That's right, the former will create and cache the variables when the application is loaded, and use the same ones going forward until it's restarted (which is why it works on redeploying). Essentially they become "static" variables, or constants, in that context.

Using a lambda/proc will make the values dynamic, in other words, the lambda/proc will be called every time the scopes are applied. For anything "dynamic" (like dates/times) that's the way to go.
