### ISSUE TITLE
Is it possible to use has_scope in another object? (like a PORO)

### ISSUE THREAD

**Issue by pinzonjulian** [heartcombo/has_scope#116]
Hey!
I've been using `has_scope` for years and it's been awesome!

I'd like to know if it's possible to use the has_scope concept outside of a controller to make it easier to test the results of the query.

My team uses the concept of `QueryObjects` extensively and I'd like to bring the same ease of use of has_scope to apply dynamic scopes to our `QueryObjects`

An example of what I'd like to do:

```ruby
class PostsController
  def index
    @posts = PostsIndexQuery.new(params: params)
  end
end

class PostsIndexQuery
  # include HasScope ?
  has_scope :name_is
  has_scope :author_name_is

  def initialize(params: )
    @result = apply_scopes(Post)
  end
end
```

The benefits from this are:
- I can test the query itself without having to create a whole system test or controller test
- It's a bit cleaner for the controller not to declare the any querying logic. Controllers with many scopes tend to become hard to read. Specially if there are multiple controller actions that use scopes.
- It can be used more easily with newer technologies in the Rails community like StimulusReflex

Thanks!

**Comment by pinzonjulian** [comment]
I'm going to go ahead and answer my question. Yes you can! (I probably should have tried this before opening the issue)

To use it you must:
1. Create your object. e.g. PostsQuery
2. include has scope in the object
  ```ruby
    include HasScope
  ```
3. Declare your scopes as usual
4. Your query must respond to a `params` method which mimics the controllers `param` method. In the example this is achieved by injecting the params from the controller and creating an attribute reader for it.

## Example query
```ruby
class PostsIndexQuery
  include HasScope
  has_scope :name_is
  has_scope :author_name_is

  def initialize(params: , relation:)
    @params = params
    @relation = relation   
  end

  attr_reader :params, :relation

  def perform
    apply_scopes(relation)
  end
end
```

## Caution
I haven't tested this thoroughly so please use this approach at your own risk. I assume `has_scope` makes assumptions about the controller for other features. I'd love some feedback on this if possible.

## Block usage

The only thing to note is that the first argument in block usage isn't the `controller` but your object itself

#### Before (when using in controller)
```ruby
has_scope :category do |controller, scope, value|
  value != 'all' ? scope.by_category(value) : scope
end
```
#### After (when using in your own object)
```ruby
# notice I renamed the first argument to query

has_scope :category do |query, scope, value|
  value != 'all' ? scope.by_category(value) : scope
end
```

`query` becomes the instance of the object itself so you can call instance methods on it that you declare in your query object.

**Comment by carlosantoniodasilva** [comment]
@pinzonjulian thanks for diving into it and posting examples here! That's right, even though has_scope has always been advertised as to be used in controllers, there's nothing super specific about it that requires it to be in a controller scope, so using it with a query object like your example should work just fine.

It uses `params` as the default for fetching the values and applying the scopes, and that is probably the only "requirement", but even that is not a requirement, as `apply_scopes` accepts the params to apply from as a second argument:

```ruby
apply_scopes(relation, my_custom_params_hash)
```

This made me think we could perhaps add some example to the docs on how to use has_scope outside of a controller. Would you like to send a PR for that? Otherwise I may tackle it at some point soon.

(I might eventually review the readme to make it less focused on controller usage, while still making that the main goal, but for now perhaps a new section about using it outside controllers will be helpful to get started)

**Comment by pinzonjulian** [comment]
Sure thing! I'll create a PR
